### ISSUE TITLE
Recommending a relevant repo

### ISSUE THREAD

**Issue by jwwthu** [huanghanchi/Quant-AI-OR-Math-Statistics#1]
Hi there,

I think my previous collection would be a good addition to your relevant repo section: https://github.com/jwwthu/DL4Stock

And the publication: Jiang W. Applications of deep learning in stock market prediction: recent progress[J]. Expert Systems with Applications, 2021: 115537. [Link](https://www.sciencedirect.com/science/article/pii/S0957417421009441)

Thank you.

**Comment by huanghanchi** [comment]
Awesome. Thanks so much!!!
